function gendcscript(dir)
%Automatically generated by meta from source files:
%dc.cmd

fn = strcat(dir, '/', 'dc.cmd');
fid = fopen(fn, 'w+');
fprintf(fid, 'redirect -tee dc.out {\n');
fprintf(fid, '\n');
fprintf(fid, '	set vhdlfiles {dff.vhdl reg.vhdl ha.vhdl fa.vhdl ha_noc.vhdl fa_noc.vhdl fir_pp.vhdl fir_cs.vhdl fir_vma.vhdl fir.vhdl}\n');
fprintf(fid, '	foreach f $vhdlfiles {\n');
fprintf(fid, '		if {[analyze -format vhdl $f] != 1} {\n');
fprintf(fid, '			quit\n');
fprintf(fid, '		}\n');
fprintf(fid, '	}\n');
fprintf(fid, '\n');
fprintf(fid, '	if {[elaborate fir] != 1} {\n');
fprintf(fid, '		quit\n');
fprintf(fid, '	}\n');
fprintf(fid, '\n');
fprintf(fid, '	create_clock -period 1.6667 clk\n');
fprintf(fid, '\n');
fprintf(fid, '	set_load 0.01 [all_outputs]\n');
fprintf(fid, '	set_driving_cell -lib_cell "IVSVTX1" [all_inputs]\n');
fprintf(fid, '	set_drive 0 clk\n');
fprintf(fid, '\n');
fprintf(fid, '	set_input_delay 0.0 [all_inputs] -clock clk\n');
fprintf(fid, '	set_output_delay 0.0 [all_outputs] -clock clk\n');
fprintf(fid, '\n');
fprintf(fid, '	set_switching_activity [all_inputs] -static_probability 0.5 -toggle_rate 0.5 -period 1.6667\n');
fprintf(fid, '\n');
fprintf(fid, '	check_design\n');
fprintf(fid, '\n');
fprintf(fid, '	if {[compile] != 1} {\n');
fprintf(fid, '		quit\n');
fprintf(fid, '	}\n');
fprintf(fid, '\n');
fprintf(fid, '	report_area\n');
fprintf(fid, '	report_timing\n');
fprintf(fid, '	report_power\n');
fprintf(fid, '}\n');
fprintf(fid, '\n');
fprintf(fid, 'exit\n');
fprintf(fid, '\n');
fclose(fid);

